language: go
go:
   - "1.13"
env:
   - GO111MODULE=on
install:
   - go mod tidy
   - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.23.6
   - go get -u github.com/kevinburke/write_mailmap
script: ./check.sh
